### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by afrubin** [rraadd88/ms_datasets#1]
I am unable to run any of the three example datasets. They all fail with the error `IOError: [Errno 2] No such file or directory: 'b161227_modeller_conf_int/btem.fasta'`.

**Comment by rraadd88** [comment]
Recent updates should fix the problem. The issue was that the some paths were mistakenly written in the `cfg/info` files. I have added all the steps needed in analyzing datasets in the updated [`README.md`](https://github.com/rraadd88/ms_datasets). 

I have successfully tested all three datasets. I hope now the issue would be resolved.
